import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/context/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
      <body className={inter.className}>
        {children}
      <Toaster richColors position="top-right"/>
      </body>
      
      </ReactQueryProvider>
    </html>
  );
}
